branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "🧪 Full Test Suite"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
      restrictions: null

  - name: staging
    protection:
      required_status_checks:
        strict: false
        contexts:
          - "⚡ Quick Check"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 0
      restrictions: null

  - name: dev
    protection:
      required_status_checks:
        strict: false
        contexts:
          - "⚡ Quick Check"
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 0
      restrictions: null
